version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers-legacy # ttps://hub.docker.com/r/circleci/ruby/
        environment:
          RAILS_ENV: test #test環境で立ち上げるため
      - image: circleci/postgres:9.4 #ttps://hub.docker.com/r/circleci/postgres
        environment:
          # POSTGRES_HOST: 127.0.0.1 #localhost
          POSTGRES_USER: task_management
          POSTGRES_DB: task_management_test #config/database.ymlで確認
          POSTGRES_HOST_AUTH_METHOD: 'trust'
    working_directory: ~/task_management
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            # このファイル内容が変更されている場合は処理をスキップします
            - v1-dependencies- # 文字列に一致するキャッシュのうち、最新のものを検索します
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load
      # - run:
      #     name: Set up DB
      #     command: |
      #       bundle exec rake db:structure:load --trace
      #       bundle exec rake db:migrate
      #     environment:
      #       DATABASE_URL: "postgres://usename@localhost:5432/task_management_test"
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec
